-- MySQL Script generated by MySQL Workbench
-- 08/16/16 10:22:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema money
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema money
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `money` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `money` ;

-- -----------------------------------------------------
-- Table `money`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NULL,
  `password` VARCHAR(255) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `money`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money`.`accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(60) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_accounts_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_accounts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `money`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `money`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `money`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `money`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `date` DATE NULL,
  `amount` DOUBLE NULL,
  PRIMARY KEY (`id`, `account_id`, `category_id`),
  INDEX `fk_transactions_accounts_idx` (`account_id` ASC),
  INDEX `fk_transactions_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_transactions_accounts`
    FOREIGN KEY (`account_id`)
    REFERENCES `money`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `money`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
